version: '3.4'

services:

  # Solr instances for running tests against

  ui:
    build: .
    environment:
     - SOLR_COLLECTION_SEARCH_PATH=http://solr-collections:8983
     - SOLR_COLLECTION_REQUEST_HANDLER=/solr/collections/select
     - SOLR_FULL_TEXT_SEARCH_PATH=http://solr-search:8983
     - SOLR_FULL_TEXT_SEARCH_REQUEST_HANDLER=/solr/discovery/select
    ports:
     - "8080:8080"
    depends_on:
      - solr-search
      - solr-collections

  solr-search:
    image: ukwa/webarchive-discovery-solr
    ports:
      - "8983:8983"

  solr-collections:
    image: ukwa/ukwa-ui-collections-solr
    ports:
      - "8984:8983"

  pa11y:
    image: min2ha/docker-pa11y
    container_name: pa11y
    command: bash -c "while ! curl -s ui:8080 > /dev/null;
      do
      echo sleeping;
      sleep 3;
      done;
      cd /code/pa11y && pa11y-ci --config /code/pa11y/config.json --json > report.json"
    volumes:
      - ./tests/pa11y/:/code/pa11y/
    cap_add:
      - SYS_ADMIN
    depends_on:
      - ui
# testhealth: ["CMD", "curl", "-f", "http://ui:8081/health"]
