name: CI/CD testing Accessibility - WCAG v2
on:
  push:
    branches: [ master-yoda-WCAG-fight ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: action-accessibility
        uses: GeopJr/action-accessibility@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

