name: CI/CD testing Accessibility - WCAG v2
on:
  push:
    branches: [ master-yoda-WCAG-fight ]

jobs:
  job_1_name:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
        
      - name: Set up Accesibility Test
        uses: GeopJr/action-accessibility@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

