name: Run CI then push to Docker Hub

on:
  push:
    tags:
      - '*'
    branches:
      - dev
jobs:
  SAST:
    name: SAST (with Sonar). Build and analyze.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Cache SonarCloud packages
        uses: actions/cache@v3
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=min2ha_ukwa-ui
  SCA-1:
    name: SCA - Software Composition Analysis scan. Workflow for Maven using Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
  SCA-2:
    name: SCA - Software Composition Analysis scan. Collect artefact.
    needs: [SAST]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/scala@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
  image_CVE_scan:
   name: CVE inspection. (Common Vulnerabilities and Exposures). Build Image and Run Image Scan
   needs: [SCA-2]
   runs-on: ubuntu-latest

   steps:
   - name: Checkout code
     uses: actions/checkout@v2

   - name: Set up Docker
     uses: docker-practice/actions-setup-docker@v1
     with:
      docker_version: '20.10.7'

   - name: Build Docker Image
     run: docker build -f Dockerfile -t myapp:latest .

 #  - name: Docker Scout Scan
 #    run: |
 #      curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
 #      sh install-scout.sh
 #      docker scout quickview
 #      docker scout cves
   - name: Docker Scout
  # You may pin to the exact commit or the version.
  # uses: docker/scout-action@b7413c99043c2a9131c0fa39cedaece80f285788
     uses: docker/scout-action@v1.2.2
     with:
      dockerhub-user: ${{ secrets.DOCKER_HUB_USERNAME }}
      # Docker Hub PAT
      dockerhub-password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      command: quickview,cves
      only-severities: critical,high
 
  push_to_docker_hub:
    name: Push Docker image to Docker Hub
    needs: [SAST,SCA-2,image_CVE_scan]
    # This uses the default metadata-action configuration, see https://github.com/docker/metadata-action
    # Pushes to master should build `ukwa/ukwa-ui:master`, pushes to dev should build `ukwa/ukwa-ui:dev`, pushes from forks should build e.g. `forker/ukwa-ui:master`.
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ github.repository }}
      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
